swagger: '2.0'
info:
  version: ''
  title: Geography API
  description: >-

    - [OAuth Scopes](#oauth-scopes)

    - [Authentication](#authentication)

    - [Available Endpoints](#available-endpoints)


    Introduction


    ## OAuth Scopes

    | UI Name                                      | Permission |
    Parameter                                     |

    |----------------------------------------------|------------|-----------------------------------------------|

    | Information & Settings                       | modify     |
    `store_v2_information`                        |

    | Information & Settings                       | read-only  |
    `store_v2_information_read_only`              |


    For more information on OAuth Scopes, see:
    [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).


    ## Authentication


    Requests can be authenticated by sending a `client_id` and `access_token`
    via `X-Auth-Client` and `X-Auth-Token` HTTP headers:


    ```http

    GET /stores/{$$.env.store_hash}/v3/catalog/summary

    host: api.bigcommerce.com

    Accept: application/json

    X-Auth-Client: {client_id}

    X-Auth-Token: {access_token}

    ```


    |Header|Parameter|Description|

    |-|-|-|

    |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
    installing an app in a BigCommerce control panel.|

    |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
    installing an app in a BigCommerce control panel.|


    For more information on Authenticating BigCommerce APIs, see:
    [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).


    ## Available Endpoints

    |
    Resource                                                                                             
    | Description                      |

    |-------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|

    |
    [Countries](https://developer.bigcommerce.com/api-reference/store-management/geography-api/countries)
    | A country or territory, identifiable by an ISO 3166 country
    code.                                              |

    |
    [States](https://developer.bigcommerce.com/api-reference/store-management/geography-api/states)      
    | A state or province, identifiable by an [ISO
    3166](https://en.wikipedia.org/wiki/ISO_3166-2) subdivision code. |
host: api.bigcommerce.com
basePath: '/stores/{$$.env.store_hash}/v2'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /countries:
    get:
      description: >-
        Get a list of all countries available. A country or territory,
        identifiable by an ISO 3166 country code.
      summary: Get A List of All Countries
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: page
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Number of pages
        - name: limit
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Count per page
        - in: query
          name: country
          type: string
        - in: query
          name: country_iso2
          type: string
        - in: query
          name: country_iso3
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              title: Country
              example:
                id: 13
                country: Australia
                country_iso2: AU
                country_iso3: AUS
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
                  resource: /countries/13/states
              type: object
              properties:
                id:
                  description: Id of the country.
                  example: 13
                  type: integer
                country:
                  description: Country name.
                  example: Australia
                  type: string
                country_iso2:
                  description: 2-letter country code.
                  example: AU
                  type: string
                country_iso3:
                  description: 3-letter country code.
                  example: AUS
                  type: string
                states:
                  title: States Resource
                  type: object
                  properties:
                    url:
                      description: ''
                      example: >-
                        https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
                      type: string
                    resource:
                      description: ''
                      example: /countries/13/states
                      type: string
          examples:
            application/json:
              - id: 1
                country: Afghanistan
                country_iso2: AF
                country_iso3: AFG
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/1/states
                  resource: /countries/1/states
              - id: 2
                country: Albania
                country_iso2: AL
                country_iso3: ALB
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/2/states
                  resource: /countries/2/states
              - id: 3
                country: Algeria
                country_iso2: DZ
                country_iso3: DZA
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/3/states
                  resource: /countries/3/states
              - id: 4
                country: American Samoa
                country_iso2: AS
                country_iso3: ASM
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/4/states
                  resource: /countries/4/states
              - id: 5
                country: Andorra
                country_iso2: AD
                country_iso3: AND
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/5/states
                  resource: /countries/5/states
              - id: 6
                country: Angola
                country_iso2: AO
                country_iso3: AGO
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/6/states
                  resource: /countries/6/states
              - id: 7
                country: Anguilla
                country_iso2: AI
                country_iso3: AIA
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/7/states
                  resource: /countries/7/states
              - id: 8
                country: Antarctica
                country_iso2: AQ
                country_iso3: "\r"
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/8/states
                  resource: /countries/8/states
              - id: 9
                country: Antigua and Barbuda
                country_iso2: AG
                country_iso3: ATG
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/9/states
                  resource: /countries/9/states
              - id: 10
                country: Argentina
                country_iso2: AR
                country_iso3: ARG
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/10/states
                  resource: /countries/10/states
              - id: 11
                country: Armenia
                country_iso2: AM
                country_iso3: ARM
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/11/states
                  resource: /countries/11/states
              - id: 12
                country: Aruba
                country_iso2: AW
                country_iso3: ABW
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/12/states
                  resource: /countries/12/states
              - id: 13
                country: Australia
                country_iso2: AU
                country_iso3: AUS
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
                  resource: /countries/13/states
              - id: 14
                country: Austria
                country_iso2: AT
                country_iso3: AUT
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/14/states
                  resource: /countries/14/states
              - id: 15
                country: Azerbaijan
                country_iso2: AZ
                country_iso3: AZE
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/15/states
                  resource: /countries/15/states
              - id: 16
                country: Bahamas
                country_iso2: BS
                country_iso3: BHS
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/16/states
                  resource: /countries/16/states
              - id: 17
                country: Bahrain
                country_iso2: BH
                country_iso3: BHR
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/17/states
                  resource: /countries/17/states
              - id: 18
                country: Bangladesh
                country_iso2: BD
                country_iso3: BGD
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/18/states
                  resource: /countries/18/states
              - id: 19
                country: Barbados
                country_iso2: BB
                country_iso3: BRB
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/19/states
                  resource: /countries/19/states
              - id: 20
                country: Belarus
                country_iso2: BY
                country_iso3: BLR
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/20/states
                  resource: /countries/20/states
              - id: 21
                country: Belgium
                country_iso2: BE
                country_iso3: BEL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/21/states
                  resource: /countries/21/states
              - id: 22
                country: Belize
                country_iso2: BZ
                country_iso3: BLZ
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/22/states
                  resource: /countries/22/states
              - id: 23
                country: Benin
                country_iso2: BJ
                country_iso3: BEN
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/23/states
                  resource: /countries/23/states
              - id: 24
                country: Bermuda
                country_iso2: BM
                country_iso3: BMU
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/24/states
                  resource: /countries/24/states
              - id: 25
                country: Bhutan
                country_iso2: BT
                country_iso3: BTN
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/25/states
                  resource: /countries/25/states
              - id: 26
                country: Bolivia
                country_iso2: BO
                country_iso3: BOL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/26/states
                  resource: /countries/26/states
              - id: 27
                country: Bosnia and Herzegovina
                country_iso2: BA
                country_iso3: BIH
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/27/states
                  resource: /countries/27/states
              - id: 28
                country: Botswana
                country_iso2: BW
                country_iso3: BWA
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/28/states
                  resource: /countries/28/states
              - id: 29
                country: Bouvet Island
                country_iso2: BV
                country_iso3: NUL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/29/states
                  resource: /countries/29/states
              - id: 30
                country: Brazil
                country_iso2: BR
                country_iso3: BRA
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/30/states
                  resource: /countries/30/states
              - id: 31
                country: British Indian Ocean Territory
                country_iso2: IO
                country_iso3: NUL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/31/states
                  resource: /countries/31/states
              - id: 32
                country: Brunei Darussalam
                country_iso2: BN
                country_iso3: BRN
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/32/states
                  resource: /countries/32/states
              - id: 33
                country: Bulgaria
                country_iso2: BG
                country_iso3: BGR
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/33/states
                  resource: /countries/33/states
              - id: 34
                country: Burkina Faso
                country_iso2: BF
                country_iso3: BFA
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/34/states
                  resource: /countries/34/states
              - id: 35
                country: Burundi
                country_iso2: BI
                country_iso3: BDI
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/35/states
                  resource: /countries/35/states
              - id: 36
                country: Cambodia
                country_iso2: KH
                country_iso3: KHM
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/36/states
                  resource: /countries/36/states
              - id: 37
                country: Cameroon
                country_iso2: CM
                country_iso3: CMR
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/37/states
                  resource: /countries/37/states
              - id: 38
                country: Canada
                country_iso2: CA
                country_iso3: CAN
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/38/states
                  resource: /countries/38/states
              - id: 39
                country: Cape Verde
                country_iso2: CV
                country_iso3: CPV
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/39/states
                  resource: /countries/39/states
              - id: 40
                country: Cayman Islands
                country_iso2: KY
                country_iso3: CYM
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/40/states
                  resource: /countries/40/states
              - id: 41
                country: Central African Republic
                country_iso2: CF
                country_iso3: CAF
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/41/states
                  resource: /countries/41/states
              - id: 42
                country: Chad
                country_iso2: TD
                country_iso3: TCD
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/42/states
                  resource: /countries/42/states
              - id: 43
                country: Chile
                country_iso2: CL
                country_iso3: CHL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/43/states
                  resource: /countries/43/states
              - id: 44
                country: China
                country_iso2: CN
                country_iso3: CHN
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/44/states
                  resource: /countries/44/states
              - id: 45
                country: Christmas Island
                country_iso2: CX
                country_iso3: NUL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/45/states
                  resource: /countries/45/states
              - id: 46
                country: Cocos (Keeling) Islands
                country_iso2: CC
                country_iso3: NUL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/46/states
                  resource: /countries/46/states
              - id: 47
                country: Colombia
                country_iso2: CO
                country_iso3: COL
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/47/states
                  resource: /countries/47/states
              - id: 48
                country: Comoros
                country_iso2: KM
                country_iso3: COM
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/48/states
                  resource: /countries/48/states
              - id: 49
                country: Congo
                country_iso2: CG
                country_iso3: COG
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/49/states
                  resource: /countries/49/states
              - id: 50
                country: 'Congo, the Democratic Republic of the'
                country_iso2: CD
                country_iso3: COD
                states:
                  url: >-
                    https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/50/states
                  resource: /countries/50/states
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Countries
  '/countries/{id}':
    get:
      description: >-
        Returns a single *Country*. 


        Gets a country. A country or territory, identifiable by an ISO 3166
        country code.
      summary: Get A Country
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: The id of the country.
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
      responses:
        '200':
          description: ''
          schema:
            title: Country
            example:
              id: 13
              country: Australia
              country_iso2: AU
              country_iso3: AUS
              states:
                url: >-
                  https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
                resource: /countries/13/states
            type: object
            properties:
              id:
                description: Id of the country.
                example: 13
                type: integer
              country:
                description: Country name.
                example: Australia
                type: string
              country_iso2:
                description: 2-letter country code.
                example: AU
                type: string
              country_iso3:
                description: 3-letter country code.
                example: AUS
                type: string
              states:
                title: States Resource
                type: object
                properties:
                  url:
                    description: ''
                    example: >-
                      https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
                    type: string
                  resource:
                    description: ''
                    example: /countries/13/states
                    type: string
          examples:
            application/json:
              id: 13
              country: Australia
              country_iso2: AU
              country_iso3: AUS
              states:
                url: >-
                  https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
                resource: /countries/13/states
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Countries
    parameters:
      - name: id
        in: path
        type: string
        required: true
  '/countries/{country_id}/states':
    get:
      description: |-
        Returns a list of *States* belonging to a *Country*. 

        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get Country States
      parameters:
        - name: country_id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Id of the country
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: state
          in: query
          required: false
          type: string
          description: Name of the state/province.
        - name: state_abbreviation
          in: query
          required: false
          type: string
          description: Abbreviation for the state/province.
        - name: page
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Number of pages
        - name: limit
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Count per page
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              title: State
              example:
                id: 208
                state: Australian Capital Territory
                state_abbreviation: ACT
                country_id: 13
              type: object
              properties:
                id:
                  description: Numeric ID of the state/province.
                  example: 208
                  type: integer
                state:
                  description: Name of the state/province.
                  example: Australian Capital Territory
                  type: string
                state_abbreviation:
                  description: Abbreviation for the state/province.
                  example: ACT
                  type: string
                country_id:
                  description: Numeric ID of the state’s/province’s associated country.
                  example: 13
                  type: integer
          examples:
            application/json:
              - id: 208
                state: Australian Capital Territory
                state_abbreviation: ACT
                country_id: 13
              - id: 209
                state: New South Wales
                state_abbreviation: NSW
                country_id: 13
              - id: 210
                state: Northern Territory
                state_abbreviation: NT
                country_id: 13
              - id: 211
                state: Queensland
                state_abbreviation: QLD
                country_id: 13
              - id: 212
                state: South Australia
                state_abbreviation: SA
                country_id: 13
              - id: 213
                state: Tasmania
                state_abbreviation: TAS
                country_id: 13
              - id: 214
                state: Victoria
                state_abbreviation: VIC
                country_id: 13
              - id: 215
                state: Western Australia
                state_abbreviation: WA
                country_id: 13
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - States
    parameters:
      - name: country_id
        in: path
        type: string
        required: true
  '/countries/{country_id}/states{id}':
    get:
      description: |-
        Returns a *State*. 

        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get A State
      produces:
        - application/json
      parameters:
        - name: country_id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Id of the country
        - name: id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Id of the states
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
      responses:
        '200':
          description: ''
          schema:
            title: State
            example:
              id: 208
              state: Australian Capital Territory
              state_abbreviation: ACT
              country_id: 13
            type: object
            properties:
              id:
                description: Numeric ID of the state/province.
                example: 208
                type: integer
              state:
                description: Name of the state/province.
                example: Australian Capital Territory
                type: string
              state_abbreviation:
                description: Abbreviation for the state/province.
                example: ACT
                type: string
              country_id:
                description: Numeric ID of the state’s/province’s associated country.
                example: 13
                type: integer
          examples:
            application/json:
              id: 208
              state: Australian Capital Territory
              state_abbreviation: ACT
              country_id: 13
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - States
    parameters:
      - name: country_id
        in: path
        type: string
        required: true
      - name: id
        in: path
        type: string
        required: true
  /countries/count:
    get:
      responses:
        '200':
          $ref: '#/responses/countResponse'
      summary: Get a Count of Countries
      tags:
        - Countries
      operationId: countriesCount
  /countries/states:
    get:
      responses:
        '200':
          $ref: '#/responses/countResponse'
      summary: Get a Count of All States
      operationId: countriesStatesCountAll
definitions:
  country_Full:
    title: country_Full
    example:
      id: 13
      country: Australia
      country_iso2: AU
      country_iso3: AUS
      states:
        url: >-
          https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
        resource: /countries/13/states
    type: object
    properties:
      id:
        description: Id of the country.
        example: 13
        type: integer
      country:
        description: Country name.
        example: Australia
        type: string
      country_iso2:
        description: 2-letter country code.
        example: AU
        type: string
      country_iso3:
        description: 3-letter country code.
        example: AUS
        type: string
      states:
        $ref: '#/definitions/countriesStates_Full'
  countriesStates_Full:
    title: countriesStates_Full
    type: object
    properties:
      url:
        description: ''
        example: >-
          https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
        type: string
      resource:
        description: ''
        example: /countries/13/states
        type: string
    description: Refers to the `states` object return in `GET` countries requests.
  countriesState_Full:
    title: countriesState_Full
    example:
      id: 208
      state: Australian Capital Territory
      state_abbreviation: ACT
      country_id: 13
    type: object
    properties:
      id:
        description: Numeric ID of the state/province.
        example: 208
        type: integer
      state:
        description: Name of the state/province.
        example: Australian Capital Territory
        type: string
      state_abbreviation:
        description: Abbreviation for the state/province.
        example: ACT
        type: string
      country_id:
        description: Numeric ID of the state’s/province’s associated country.
        example: 13
        type: integer
    description: 'Refers to the state returned in `GET` states requests. '
  countries_Resp:
    type: object
    properties: {}
  count_Full:
    type: object
    properties:
      count:
        type: integer
        minimum: 1
securityDefinitions:
  X-Auth-Token:
    type: apiKey
    name: X-Auth-Token
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
  X-Auth-Client:
    type: apiKey
    name: X-Auth-Client
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
security:
  - X-Auth-Token: []
  - X-Auth-Client: []
tags:
  - name: Countries
  - name: States
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
responses:
  countriesResponse:
    description: ''
    schema:
      type: object
      properties: {}
  countriesStatesResponse:
    description: ''
    schema:
      type: object
      properties: {}
  countriesCollectionResponse:
    description: ''
    schema:
      type: object
      properties: {}
  countriesStatesCollectionResponse:
    description: ''
    schema:
      type: object
      properties: {}
  countResponse:
    description: ''
    schema:
      $ref: '#/definitions/count_Full'
    examples:
      application/json:
        count: 241
