{
  "swagger": "2.0",
  "info": {
    "version": "",
    "title": "Countries",
    "description": "The Product resource represents a product in your BigCommerce store. You can retrieve it to see information associated with the specified merchandise.\n\nUsing the related subresources, you can also manage pricing, images, product modifiers, variants, etc.\n\n**On This Page**\n- [Authentication](#authentication)\n- [OAuth Scopes](#oauth-scopes)\n- [Subresources](#subresources)\n- [Additional Resources](#resources)\n---\n\n## Authentication\nYou can authenticate requests by sending a `client_id` and `access_token` via `X-Auth-Client` and `X-Auth-Token` HTTP headers:\n\n```http\nGET /stores/{$$.env.store_hash}/v3/catalog/summary\nhost: api.bigcommerce.com\nAccept: application/json\nX-Auth-Client: {client_id}\nX-Auth-Token: {access_token}\n```\nYou can obtain the `client_id` and `access_token` using either of the following methods:\n- [Creating API account](https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#obtaining-store-api-credentials)\n- [Installing an app in the BigCommerce control panel](https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#obtaining-app-api-credentials)\n---\n\n## OAuth Scopes\nScope limits ability to read or modify data. To interact with the Products resource, set the scope to the minimum level needed to accomplish your specific task. \n\n| UI Name  | Permission | Parameter                     |\n|----------|------------|-------------------------------|\n| Products | modify     | `store_v2_products`           |\n| Products | read-only  | `store_v2_products_read_only` |\n\nFor more information on OAuth Scopes, see the [REST API Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#oauth-scopes) page.\n\n---\n\n## Subresources\nThe Products resource contains many subresources, outlined in the following sections.\n\n### Bulk Pricing Rules\nSet prices for individual items or item groups based on the number of items ordered. For more details, see [Bulk Pricing](https://support.bigcommerce.com/s/article/Bulk-Pricing).\n\n### Complex Rules\nDefine specific attributes that alter a product without changing the product's SKU. For more details, see [Product Option: Rules](https://support.bigcommerce.com/s/article/Product-Options-Rules-Video#).\n\n### Custom Fields\nCreate and display additional product information on the product page. For more details, see [Custom Fields](https://support.bigcommerce.com/s/article/Custom-Fields). \n\n### Images\nAdd and manage images for specific products. For more details, see the _Images & videos_ section of the [Adding Products](https://support.bigcommerce.com/s/article/Adding-Products-v3#images) page.\n\n### Metafields\nView, create, and modify meta information associated with products.\n\n### Modifiers\nModifiers differ in capabilities depending on which version you are using. For more information, see the version comparison section on the [Product Options](https://support.bigcommerce.com/s/article/Product-Options-v3#compare) page.\n\n### Modifier Images\nAdd and manage images for specific product modifiers.\n\n### Modifier Values\nSet and manage the values associated with defined product modifiers.\n\n### Reviews\nView and manage the comments customers leave on product pages. For more details, see [Managing Reviews](https://support.bigcommerce.com/s/article/Managing-Reviews). \n\n### Variants\nView, add, and manage product variations that alter the product's SKU. For more details, see [Variations](https://support.bigcommerce.com/s/article/Product-Options-v3#variations).\n\n### Variant Options\nManage the variant choices displayed on product pages. For more details, see the _Variations_ section on the [Product Options](https://support.bigcommerce.com/s/article/Product-Options-v3#variations) page. \n\n### Variant Option Values\nAdd and manage the values associated with specified variant options. For more details, see the _Variations_ section on the [Product Options](https://support.bigcommerce.com/s/article/Product-Options-v3#variations) page. \n\n### Variant Metafields\nView, create, and modify meta information associated with product variants.\n\n### Videos\nAdd and manage product videos hosted on YouTube. For more details, see the _Images & videos_ section of the [Adding Products](https://support.bigcommerce.com/s/article/Adding-Products-v3#images) page.\n\n---\n\n## Additional Information\n**Webhooks**\n- [Product](/api-docs/getting-started/webhooks/webhook-events#webhook-events_products)\n\n**Related API Resources**\n- [Brand](#)\n- [Category](#)\n- [Summary](#)\n- [Variant](#)",
        "termsOfService": "https://www.bigcommerce.com/terms/",
    "license": {
      "name": ""
    },
    "contact": {
      "name": "BigCommerce Developer Documentation",
      "url": "https://developer.bigcommerce.com/"
    }
  },
  "host": "api.bigcommerce.com",
  "basePath": "/stores/{$$.env.store_hash}/v2",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/countries": {
      "get": {
        "description": "Get a list of all countries available. A country or territory, identifiable by an ISO 3166 country code.",
        "summary": "Get All Countries",
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Number of pages"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Count per page"
          },
          {
            "in": "query",
            "name": "country",
            "type": "string"
          },
          {
            "in": "query",
            "name": "country_iso2",
            "type": "string"
          },
          {
            "in": "query",
            "name": "country_iso3",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/countryCollection_Resp"
          }
        },
        "tags": [
          "Countries"
        ]
      }
    },
    "/countries/{id}": {
      "get": {
        "description": "Returns a single *Country*. \n\nGets a country. A country or territory, identifiable by an ISO 3166 country code.",
        "summary": "Get a Country",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "The id of the country."
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/countriesResponse"
          }
        },
        "tags": [
          "Countries"
        ]
      },
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "type": "string",
          "required": true
        }
      ]
    },
    "/countries/{country_id}/states": {
      "get": {
        "description": "Returns a list of *States* belonging to a *Country*. \n\nA state or province, identifiable by an ISO 3166 subdivision code.",
        "summary": "Get All Country's States",
        "parameters": [
          {
            "name": "country_id",
            "in": "path",
            "required": true,
            "type": "integer",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Id of the country"
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "state",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Name of the state/province."
          },
          {
            "name": "state_abbreviation",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Abbreviation for the state/province."
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Number of pages"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Count per page"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/countriesStatesCollectionResponse"
          }
        },
        "tags": [
          "Countries States"
        ],
        "produces": [
          "application/json"
        ]
      },
      "parameters": [
        {
          "name": "country_id",
          "in": "path",
          "type": "string",
          "required": true
        }
      ]
    },
    "/countries/{country_id}/states{id}": {
      "get": {
        "description": "Returns a *State*. \n\nA state or province, identifiable by an ISO 3166 subdivision code.",
        "summary": "Get a Country's State",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "country_id",
            "in": "path",
            "required": true,
            "type": "integer",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Id of the country"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Id of the states"
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/countriesStatesResponse"
          }
        },
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "tags": [
          "Countries States"
        ]
      },
      "parameters": [
        {
          "name": "country_id",
          "in": "path",
          "type": "string",
          "required": true
        },
        {
          "name": "id",
          "in": "path",
          "type": "string",
          "required": true
        }
      ]
    },
    "/countries/count": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/responses/countResponse"
          }
        },
        "summary": "Get a Count of All Countries",
        "tags": [
          "Countries Count"
        ],
        "operationId": "countriesCount",
        "description": "Returns a count of all countries."
      }
    },
    "/countries/states/count": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/responses/countResponse"
          }
        },
        "summary": "Get a Count of All States",
        "tags": [
          "Countries State Count"
        ],
        "description": "Returns a count of all states."
      }
    },
    "/countries/states": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/responses/countriesStatesCollectionResponse"
          }
        },
        "summary": "Get All States",
        "tags": [
          "Countries States"
        ],
        "description": "Returns a list of all states."
      }
    },
    "/countries/{country_id}/states/count": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/responses/countResponse"
          }
        },
        "summary": "Get a Count of Country's States ",
        "tags": [
          "Countries State Count"
        ],
        "description": "Returns a count of a country's states.",
        "produces": [
          "application/json"
        ]
      },
      "parameters": [
        {
          "name": "country_id",
          "in": "path",
          "type": "string",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "country_Full": {
      "title": "country_Full",
      "example": {
        "id": 13,
        "country": "Australia",
        "country_iso2": "AU",
        "country_iso3": "AUS",
        "states": {
          "url": "https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states",
          "resource": "/countries/13/states"
        }
      },
      "allOf": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "description": "Id of the country.",
              "example": 13
            }
          }
        },
        {
          "$ref": "#/definitions/country_Base"
        },
        {
          "type": "object",
          "properties": {
            "states": {
              "$ref": "#/definitions/countriesStates_Full"
            }
          }
        }
      ]
    },
    "countriesStates_Full": {
      "title": "countriesStates_Full",
      "type": "object",
      "properties": {
        "url": {
          "description": "",
          "example": "https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states",
          "type": "string"
        },
        "resource": {
          "description": "",
          "example": "/countries/13/states",
          "type": "string"
        }
      },
      "description": "Refers to the `states` object return in `GET` countries requests."
    },
    "countriesState_Full": {
      "title": "countriesState_Full",
      "example": {
        "id": 208,
        "state": "Australian Capital Territory",
        "state_abbreviation": "ACT",
        "country_id": 13
      },
      "type": "object",
      "properties": {
        "id": {
          "description": "Numeric ID of the state/province.",
          "example": 208,
          "type": "integer"
        },
        "state": {
          "description": "Name of the state/province.",
          "example": "Australian Capital Territory",
          "type": "string"
        },
        "state_abbreviation": {
          "description": "Abbreviation for the state/province.",
          "example": "ACT",
          "type": "string"
        },
        "country_id": {
          "description": "Numeric ID of the state’s/province’s associated country.",
          "example": 13,
          "type": "integer"
        }
      },
      "description": "Refers to the state returned in `GET` states requests. "
    },
    "country_Base": {
      "type": "object",
      "title": "country_Base",
      "properties": {
        "country": {
          "type": "string",
          "example": "Australia",
          "description": "Country name."
        },
        "country_iso2": {
          "type": "string",
          "description": "2-letter country code.",
          "example": "AU"
        },
        "country_iso3": {
          "type": "string",
          "description": "3-letter country code.",
          "example": "AUS"
        }
      }
    },
    "count_Full": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "minimum": 1
        }
      }
    }
  },
  "securityDefinitions": {
    "X-Auth-Token": {
      "type": "apiKey",
      "name": "X-Auth-Token",
      "in": "header",
      "description": "### OAuth Scopes\n|  **UI Name** | **Permission** | **Parameter** |\n| --- | --- | --- |\n|  Information & Settings | modify | `store_v2_information` |\n|  Information & Settings | read-only | `store_v2_information_read_only` |\n\n### Headers\n\n|Header|Parameter|Description|\n|-|-|-|\n|`X-Auth-Client`|`client_id`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n|`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n\n### Example\n\n```http\nGET /stores/{$$.env.store_hash}/v3/catalog/summary\nhost: api.bigcommerce.com\nContent-Type: application/json\nX-Auth-Client: {client_id}\nX-Auth-Token: {access_token}\n```\n\n* For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). "
    },
    "X-Auth-Client": {
      "type": "apiKey",
      "name": "X-Auth-Client",
      "in": "header",
      "description": "### OAuth Scopes\n|  **UI Name** | **Permission** | **Parameter** |\n| --- | --- | --- |\n|  Information & Settings | modify | `store_v2_information` |\n|  Information & Settings | read-only | `store_v2_information_read_only` |\n\n### Headers\n\n|Header|Parameter|Description|\n|-|-|-|\n|`X-Auth-Client`|`client_id`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n|`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n\n### Example\n\n```http\nGET /stores/{$$.env.store_hash}/v3/catalog/summary\nhost: api.bigcommerce.com\nContent-Type: application/json\nX-Auth-Client: {client_id}\nX-Auth-Token: {access_token}\n```\n\n* For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). "
    }
  },
  "security": [
    {
      "X-Auth-Token": []
    },
    {
      "X-Auth-Client": []
    }
  ],
  "tags": [
    {
      "name": "Countries"
    },
    {
      "name": "Countries Count"
    },
    {
      "name": "Countries States"
    },
    {
      "name": "Countries State Count"
    }
  ],
  "x-stoplight": {
    "docs": {
      "includeDownloadLink": true,
      "showModels": false
    }
  },
  "responses": {
    "countriesResponse": {
      "description": "",
      "schema": {
        "$ref": "#/definitions/country_Full"
      },
      "examples": {
        "application/json": {
          "id": 1,
          "country": "Afghanistan",
          "country_iso2": "AF",
          "country_iso3": "AFG",
          "states": {
            "url": "https://api.bigcommerce.com/stores/h10wocxy6s/v2/countries/1/states",
            "resource": "/countries/1/states"
          }
        }
      }
    },
    "countriesStatesResponse": {
      "description": "",
      "schema": {
        "$ref": "#/definitions/countriesState_Full"
      }
    },
    "countryCollection_Resp": {
      "description": "",
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/country_Full"
        }
      },
      "examples": {
        "application/json": "[\n  {\n    \"id\": 1,\n    \"country\": \"Afghanistan\",\n    \"country_iso2\": \"AF\",\n    \"country_iso3\": \"AFG\",\n    \"states\": {\n      \"url\": \"https:\\/\\/api.bigcommerce.com\\/stores\\/store_hash\\/v2\\/countries\\/1\\/states\",\n      \"resource\": \"\\/countries\\/1\\/states\"\n    }\n  },\n  {\n    \"id\": 2,\n    \"country\": \"Albania\",\n    \"country_iso2\": \"AL\",\n    \"country_iso3\": \"ALB\",\n    \"states\": {\n      \"url\": \"https:\\/\\/api.bigcommerce.com\\/stores\\/store_hash\\/v2\\/countries\\/2\\/states\",\n      \"resource\": \"\\/countries\\/2\\/states\"\n    }\n  },\n  // ...\n  ]"
      }
    },
    "countriesStatesCollectionResponse": {
      "description": "",
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/countriesState_Full"
        }
      }
    },
    "countResponse": {
      "description": "",
      "schema": {
        "$ref": "#/definitions/count_Full"
      },
      "examples": {
        "application/json": {
          "count": 241
        }
      }
    }
  }
}