{
  "swagger": "2.0",
  "info": {
    "version": "2",
    "title": "Customer Groups",
    "description": "- [OAuth Scopes](#oauth-scopes)\n- [Authentication](#authentication)\n- [Available Endpoints](#available-endpoints)\n- [Usage Notes](#usage-notes)\n- [Resources](#resources)\n\nCreate and Manage Customers, Customer Addresses, and Customer Groups. Additionally, validate customer passwords.\n\nTo learn more about Customers see [here](/api-docs/customers/customers-subscribers-overview). \n\n## OAuth Scopes\n| UI Name                                      | Permission | Parameter                                     |\n|----------------------------------------------|------------|-----------------------------------------------|\n| Customers                                    | modify     | `store_v2_customers`                          |\n| Customers                                    | read-only  | `store_v2_customers_read_only`                |\n\nFor more information on OAuth Scopes, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).\n\n## Authentication\n\nRequests can be authenticated by sending a `client_id` and `access_token` via `X-Auth-Client` and `X-Auth-Token` HTTP headers:\n\n```http\nGET /stores/{$$.env.store_hash}/v3/catalog/summary\nhost: api.bigcommerce.com\nAccept: application/json\nX-Auth-Client: {client_id}\nX-Auth-Token: {access_token}\n```\n\n|Header|Parameter|Description|\n|-|-|-|\n|`X-Auth-Client`|`client_id`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n|`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n\nFor more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).\n\n## Available Endpoints\n| Resource / Endpoint                     | Description                                                                   |\n|-----------------------------------------|-------------------------------------------------------------------------------|\n| Customers                               | Identity and account details for customers shopping on BigCommerce stores     |\n| Customers Addresses                     | Postal address belonging to a customer.                                       |\n| Customers Groups                        | Groupings of customers who share the same level of access and discounts       |\n| Customers Validate Password             | Validate customer passwords                                                   |\n\n## Usage Notes\n\n**Customer Groups**\n* Customer Groups are only available on specific plans.\n\n**Customers vs. Subscribers**\n* A subscriber is not always a customer. Someone can sign up for the newsletter only and not create an account.\n* A customer is not always a subscriber. Signing up for the newsletter is a separate action from creating an account and purchasing an item.\n* A customer and a subscriber can be the same. If a shopper checks out on the storefront, creates an account and opts into the newsletter, they are a customer and a subscriber.\n\n## Resources\n\n### Related APIs / Endpoints\n  [Customer Login API](https://developer.bigcommerce.com/api-docs/customers/customer-login-api)\n- [Current Customer API](https://developer.bigcommerce.com/api-docs/customers/current-customer-api)\n- [Customers API (v3)](https://developer.bigcommerce.com/api-reference/customer-subscribers/v3-customers-api)\n- [Subscribers API](https://developer.bigcommerce.com/api-reference/customer-subscribers/subscribers-api)\n\n### Webhooks\n- [Customers](https://developer.bigcommerce.com/api-docs/getting-started/webhooks/webhook-events#webhook-events_customer)"
  },
  "host": "api.bigcommerce.com",
  "basePath": "/stores/{$$.env.store_hash}/v2",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/customer_groups": {
      "get": {
        "description": "Returns a list of *Customer Groups*. Default sorting is by customer-group id, from lowest to highest.",
        "summary": "Get All Customer Groups",
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Number of pages"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Count per page"
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Filter customer groups by exact name match. Can use `name:like` to filter using a fuzzy matching method. This is good for implementing search."
          },
          {
            "name": "is_default",
            "in": "query",
            "required": false,
            "type": "boolean",
            "description": "If customers who signup are added to this group by default"
          },
          {
            "$ref": "#/parameters/is_group_for_guests"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/customerGroup_Full"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 1,
                  "name": "B2B",
                  "is_default": false,
                  "category_access": {
                    "type": "all"
                  },
                  "discount_rules": [
                    {
                      "type": "price_list",
                      "price_list_id": 1
                    }
                  ]
                },
                {
                  "id": 2,
                  "name": "5% Discount",
                  "is_default": false,
                  "category_access": {
                    "type": "specific",
                    "categories": [
                      18,
                      19,
                      23,
                      34
                    ]
                  },
                  "discount_rules": [
                    {
                      "type": "all",
                      "method": "percent",
                      "amount": "5.0000"
                    }
                  ],
                  "is_group_for_guests": true
                }
              ],
              "Response Schema": [
                {
                  "id": -17214385,
                  "name": "cupidatat labore",
                  "is_default": true,
                  "category_access": {},
                  "discount_rules": [
                    {
                      "type": "sunt in ad ea",
                      "method": "nisi aliquip et ut magna",
                      "amount": "consectetur anim sed"
                    },
                    {
                      "type": "enim nulla magna",
                      "method": "est sed adipisicing ut",
                      "amount": "nostrud dolore sunt pariatur"
                    },
                    {
                      "type": "consequat ipsum sunt ut",
                      "method": "dolor tempor labore",
                      "amount": "aliquip eiusmo"
                    }
                  ]
                }
              ]
            }
          }
        },
        "tags": [
          "Customer Groups"
        ],
        "operationId": "getAllCustomerGroups"
      },
      "post": {
        "summary": "Create a Customer Group",
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "X-Auth-Client",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "X-Auth-Token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/customerGroup_Post"
            },
            "x-examples": {
              "application/json": {
                "name": "Student Discounts",
                "discount_rules": [
                  {
                    "type": "price_list",
                    "price_list_id": 3
                  }
                ]
              },
              "Give a 5% Discount to All Members": "{\n    \"name\": \"Student Discounts\",\n    \"discount_rules\": \n    [{\n        \"type\": \"all\",\n        \"method\": \"percent\",\n        \"amount\": 5.00\n    }]\n}",
              "Restrict Categories for Group": {
                "name": "Bulk Purchasers",
                "category_access": {
                  "type": "specific",
                  "categories": [
                    7,
                    12,
                    20
                  ]
                }
              },
              "Assign New Customers to a Group": "{\n  \"name\": \"Retail Customers\",\n  \"is_default\": true\n}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customerGroup_Full"
            },
            "examples": {
              "application/json": {
                "name": "5% Discount",
                "is_default": false,
                "category_access": {
                  "type": "specific",
                  "categories": [
                    18,
                    19,
                    23,
                    34
                  ]
                },
                "discount_rules": [
                  {
                    "type": "all",
                    "method": "percent",
                    "amount": "5.0000"
                  }
                ],
                "is_group_for_guests": true
              }
            }
          }
        },
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "description": "Creates a *Customer Group*. \n\n**Required Fields**\n* name",
        "tags": [
          "Customer Groups"
        ],
        "operationId": "createACustomerGroup"
      },
      "delete": {
        "description": "By default, it deletes all *Customer Groups*. \n\nAll existing customers are unassigned from the group when it is deleted.",
        "summary": "Delete Customer Groups",
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          }
        ],
        "responses": {
          "204": {
            "description": ""
          }
        },
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "tags": [
          "Customer Groups"
        ],
        "operationId": "deleteAllCustomerGroups"
      }
    },
    "/customer_groups/{customer_group_id}": {
      "get": {
        "description": "Returns a *Customer Group*.",
        "summary": "Get a Customer Group",
        "parameters": [
          {
            "name": "customer_group_id",
            "in": "path",
            "type": "integer",
            "required": true,
            "description": "Id of the customer group"
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Number of pages"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "number",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "Count per page"
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Name of the customer groups"
          },
          {
            "name": "is_default",
            "in": "query",
            "required": false,
            "type": "boolean",
            "description": "If customers who signup are added to this group by default"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customerGroup_Full"
            },
            "examples": {
              "application/json": {
                "id": 2,
                "name": "5% Discount",
                "is_default": false,
                "category_access": {
                  "type": "specific",
                  "categories": [
                    18,
                    19,
                    23,
                    34
                  ]
                },
                "discount_rules": [
                  {
                    "type": "all",
                    "method": "percent",
                    "amount": "5.0000"
                  }
                ],
                "is_group_for_guests": true
              }
            }
          }
        },
        "tags": [
          "Customer Groups"
        ],
        "operationId": "getACustomerGroup"
      },
      "delete": {
        "description": "Deletes a *Customer Group*. \n\n**Notes**\n\nAll existing customers are unassigned from the group when it is deleted.",
        "summary": "Delete a Customer Group",
        "parameters": [
          {
            "name": "customer_group_id",
            "in": "path",
            "required": true,
            "type": "integer",
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "description": "The id of the customer group."
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          }
        ],
        "responses": {
          "204": {
            "description": ""
          }
        },
        "tags": [
          "Customer Groups"
        ],
        "operationId": "deleteACustomerGroup"
      },
      "parameters": [
        {
          "name": "customer_group_id",
          "in": "path",
          "type": "integer",
          "required": true,
          "description": "Id of the customer group"
        }
      ],
      "put": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customerGroup_Full"
            },
            "examples": {
              "application/json": {
                "id": 2,
                "name": "25% Discount",
                "is_default": false,
                "category_access": {
                  "type": "specific",
                  "categories": [
                    18,
                    19,
                    23,
                    34
                  ]
                },
                "discount_rules": [
                  {
                    "type": "all",
                    "method": "percent",
                    "amount": "25.0000"
                  }
                ],
                "is_group_for_guests": true
              },
              "Response Schema": {
                "id": -16565096,
                "name": "consequat proident",
                "is_default": true,
                "category_access": {},
                "discount_rules": [
                  {
                    "type": "mollit laborum dolor enim",
                    "method": "fugiat magna sint nostrud",
                    "amount": "ea eiusmod ut ex"
                  },
                  {
                    "type": "aliquip laborum",
                    "method": "Excepteur",
                    "amount": "aliquip cillum est do"
                  }
                ]
              }
            }
          }
        },
        "summary": "Update a Customer Group",
        "parameters": [
          {
            "in": "path",
            "name": "customer_group_id",
            "type": "integer",
            "required": true,
            "description": "Id of the customer group"
          },
          {
            "in": "header",
            "name": "Accepts",
            "type": "string",
            "required": true
          },
          {
            "in": "header",
            "name": "Content-Type",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/customerGroup_Full"
            },
            "x-examples": {
              "application/json": {
                "name": "25% off",
                "discount_rules": [
                  {
                    "type": "all",
                    "method": "percent",
                    "amount": "25.0000"
                  }
                ]
              },
              "Bulk Update Rules": {
                "discount_rules": [
                  {
                    "type": "all",
                    "method": "percent",
                    "amount": 2.5
                  },
                  {
                    "type": "product",
                    "product_id": 33,
                    "method": "percent",
                    "amount": 5
                  },
                  {
                    "type": "category",
                    "category_id": 7,
                    "method": "price",
                    "amount": 12
                  }
                ]
              },
              "Price Lists": "{\n  \"name\": \"Student Discounts\",\n  \"discount_rules\": [\n    {\n      \"type\": \"price_list\",\n      \"price_list_id\": 3\n    }\n  ]\n}"
            }
          }
        ],
        "description": "Updates a *Customer Group*.\n\n**Notes**\n\nAny combination of fields can be updated at once. Discount rules are treated in bulk. The entire set of rules is overwritten when a request is sent.",
        "tags": [
          "Customer Groups"
        ],
        "operationId": "updateACustomerGroup"
      }
    },
    "/customer_groups/count": {
      "get": {
        "description": "Returns a count of all *Customer Groups*. ",
        "summary": "Get a Count of Customer Groups",
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": "",
            "default": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/count_Full"
            },
            "examples": {
              "application/json": {
                "count": 27
              }
            }
          }
        },
        "x-unitTests": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "tags": [
          "Customer Groups"
        ],
        "operationId": "getACountOfCustomerGroups"
      }
    }
  },
  "definitions": {
    "categoryAccessLevel_Full": {
      "title": "categoryAccessLevel_Full",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "all",
            "specific",
            "none"
          ],
          "description": "+ `all` - Customers can access all categories\n + `specific`  - Customers can access a specific list of categories\n+ `none` - Customers are prevented from viewing any of the categories in this group."
        },
        "categories": {
          "description": "Is an array of category IDs and should be supplied only if `type` is specific.",
          "type": "array",
          "example": "18,19,23,34",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "count_Full": {
      "title": "count_Full",
      "example": {
        "count": 27
      },
      "type": "object",
      "properties": {
        "count": {
          "description": "",
          "example": 27,
          "type": "number"
        }
      }
    },
    "customerGroup_Full": {
      "title": "customerGroup_Full",
      "type": "object",
      "description": "When creating a customer group category discount using the API it defaults to \"products in this category and its subcategories\". In the [Control Panel](https://support.bigcommerce.com/s/article/Customer-Groups#pricing) this can be changed to either \"products in this category only\" or \"products in this category and its subcategories\". There are currently no settings to change this behavior via API.",
      "properties": {
        "id": {
          "description": "Id of the customer group",
          "example": 1,
          "type": "integer"
        },
        "name": {
          "description": "Name of the group",
          "example": "Wholesale",
          "type": "string"
        },
        "is_default": {
          "description": "Determines whether new customers are assigned to this group by default.",
          "example": false,
          "type": "boolean"
        },
        "category_access": {
          "$ref": "#/definitions/categoryAccessLevel_Full"
        },
        "discount_rules": {
          "description": "A collection of discount rules that are automatically applied to customers who are members of the group",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "price_list",
                  "all",
                  "category",
                  "product"
                ]
              },
              "method": {
                "type": "string",
                "enum": [
                  "percent",
                  "fixed",
                  "price"
                ]
              },
              "amount": {
                "type": "string",
                "example": "\"5.0000\" (Float, Float as String, Integer)",
                "description": "A float that specifies the value applied to the price modified"
              },
              "price_list_id": {
                "type": "integer",
                "example": 3,
                "description": "If a customer group is assigned to a price list,`method` and `amount` are not shown. `type` and `price_list_id` are returned."
              }
            }
          }
        },
        "is_group_for_guests": {
          "type": "boolean",
          "description": "If the groups is for guests. There can only be one customer group for guests at a time."
        }
      }
    },
    "customerGroup_Post": {
      "title": "customerGroup_Post",
      "type": "object",
      "description": "When creating a customer group category discount using the API it defaults to \"products in this category and its subcategories\". In the [Control Panel](https://support.bigcommerce.com/s/article/Customer-Groups#pricing) this can be changed to either \"products in this category only\" or \"products in this category and its subcategories\". There are currently no settings to change this behavior via API.",
      "properties": {
        "name": {
          "description": "Name of the group",
          "example": "Wholesale",
          "type": "string"
        },
        "is_default": {
          "description": "Determines whether new customers are assigned to this group by default.",
          "example": false,
          "type": "boolean"
        },
        "category_access": {
          "$ref": "#/definitions/categoryAccessLevel_Full"
        },
        "discount_rules": {
          "description": "A collection of discount rules that are automatically applied to customers who are members of the group",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "price_list",
                  "all",
                  "category",
                  "product"
                ]
              },
              "method": {
                "type": "string",
                "enum": [
                  "percent",
                  "fixed",
                  "price"
                ]
              },
              "amount": {
                "type": "string",
                "example": "\"5.0000\" (Float, Float as String, Integer)",
                "description": "A float that specifies the value applied to the price modified"
              },
              "price_list_id": {
                "type": "integer",
                "example": 3,
                "description": "If a customer group is assigned to a price list,`method` and `amount` are not shown. `type` and `price_list_id` are returned."
              }
            }
          }
        },
        "is_group_for_guests": {
          "type": "boolean",
          "description": "If the groups is for guests. There can only be one customer group for guests at a time."
        }
      }
    }
  },
  "tags": [
    {
      "name": "Customer Groups"
    }
  ],
  "securityDefinitions": {
    "X-Auth-Token": {
      "type": "apiKey",
      "name": "X-Auth-Token",
      "in": "header",
      "description": "### OAuth Scopes\n|  **UI Name** | **Permission** | **Parameter** |\n| --- | --- | --- |\n|  Customers | modify | `store_v2_customers` |\n|  Customers | read-only | `store_v2_customers_read_only` |\n\n### Headers\n\n|Header|Parameter|Description|\n|-|-|-|\n|`X-Auth-Client`|`client_id`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n|`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n\n### Example\n\n```http\nGET /stores/{$$.env.store_hash}/v3/catalog/summary\nhost: api.bigcommerce.com\nContent-Type: application/json\nX-Auth-Client: {client_id}\nX-Auth-Token: {access_token}\n```\n\n* For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). "
    },
    "X-Auth-Client": {
      "type": "apiKey",
      "name": "X-Auth-Client",
      "in": "header",
      "description": "### OAuth Scopes\n|  **UI Name** | **Permission** | **Parameter** |\n| --- | --- | --- |\n|  Customers | modify | `store_v2_customers` |\n|  Customers | read-only | `store_v2_customers_read_only` |\n\n### Headers\n\n|Header|Parameter|Description|\n|-|-|-|\n|`X-Auth-Client`|`client_id`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n|`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|\n\n### Example\n\n```http\nGET /stores/{$$.env.store_hash}/v3/catalog/summary\nhost: api.bigcommerce.com\nContent-Type: application/json\nX-Auth-Client: {client_id}\nX-Auth-Token: {access_token}\n```\n\n* For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). "
    }
  },
  "security": [
    {
      "X-Auth-Token": []
    },
    {
      "X-Auth-Client": []
    }
  ],
  "parameters": {
    "customer_id": {
      "name": "customer_id",
      "in": "path",
      "type": "integer",
      "required": true,
      "description": "Id of the customer"
    },
    "customer_group_id": {
      "name": "customer_group_id",
      "in": "path",
      "type": "integer",
      "required": true,
      "description": "Id of the customer group"
    },
    "customer_address_id": {
      "name": "customer_address_id",
      "in": "path",
      "type": "integer",
      "description": "Id of the customer address.",
      "required": true
    },
    "is_group_for_guests": {
      "name": "is_group_for_guests",
      "in": "query",
      "type": "boolean",
      "description": "If the groups is for guests. There can only be one customer group for guests at a time."
    }
  },
  "x-stoplight": {
    "docs": {
      "includeDownloadLink": true,
      "showModels": false
    }
  }
}